### ISSUE TITLE
Is there any vanilla JavaScript version of this library?

### ISSUE THREAD

**Issue by Sumon-TWeb** [netless-io/video-js-plugin#5]
To use current netless-io/video-js-plugin we required to include react, react-dom as dependencies. But I want to use inside an angular project. So if there is any Vanilla JavaScript version available of this library then no need to include react unnecessary.
Thank You.

**Comment by hyrious** [comment]
No.

The plugin API in white-web-sdk [requires a react component to be returned](https://hyrious.me/npm-browser/?q=white-web-sdk%402.16.36%2Fpackage%2Ftypes%2Findex.d.ts%3A459), besides white-web-sdk also [has a dependency of react](https://hyrious.me/npm-browser/?q=white-web-sdk%402.16.36%2Fpackage%2Fpackage.json%3A24). So in fact you cannot get rid of a copy of react anyway, the sdk is heavily built on top of that.

It is recommended to try [window manager](https://github.com/netless-io/window-manager) with [fastboard](https://github.com/netless-io/fastboard) if you're new to the whiteboard sdk, the former [defines a nicer plugin api called "netless app"](https://github.com/netless-io/window-manager/blob/master/docs/develop-app.md) which does not depend on any frameworks or abstract classes. It also includes built-in apps of [media player](https://github.com/netless-io/window-manager#add-audio-and-video-to-the-whiteboard) and docs viewer that are ready to use without any extra installation steps. (However keep in mind that all of them are built on top of white-web-sdk, so a dependency of react will not vanish.)

**Comment by Sumon-TWeb** [comment]
Okay Thanks for information @hyrious. I will try window manager. I think we can also use window manager with white-web-sdk, right ?

**Comment by hyrious** [comment]
Yes, the relations between them are as follows:

- `white-web-sdk` provides data sync service and whiteboard render engine
- `@netless/window-manager` wraps white-web-sdk, provides multi-window features and the api for netless apps
  - `@netless/app-media-player` the player app that implements the netless app api, built-in in window-manager
- `@netless/fastboard` wraps white-web-sdk and window-manager, provides many simplified api for common use case

Although you can directly use window-manager, we found that [the initialization code](https://github.com/netless-io/fastboard/blob/e74bd7eb848aac05056fad38a78bef69668f4280/packages/fastboard-core/src/impl/FastboardApp.ts#L580) is a bit complicated for everyone to write correctly, that's why we made fastboard to simplify users' works.

**Comment by Sumon-TWeb** [comment]
Okay. Thanks. I will follow this.
